# Generated by Django 2.1.2 on 2019-02-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auto_scan',
            field=models.BooleanField(default=True),
        ),
    ]
